sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Let's create an image with dockerfile"
  - docker build -t myunghoon/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true myunghoon/docker-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-web-app"
  env: "Dockerwebapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-470502063302"
  bucket_path: "docker-web-app"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
